spring:
  application:
    name: eureka-server
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: peer1
server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver1
  client:
    serviceUrl:
      defaultZone: http://eurekaserver2:8072/eureka/,http://eurekaserver3:8073/eureka/

---
spring:
  config:
    activate:
      on-profile: peer2
server:
  port: 8072
eureka:
  instance:
    hostname: eurekaserver2
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8070/eureka/,http://eurekaserver3:8073/eureka/

---
spring:
  config:
    activate:
      on-profile: peer3
server:
  port: 8073
eureka:
  instance:
    hostname: eurekaserver3
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8070/eureka/,http://eurekaserver2:8072/eureka/